//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.08 at 12:23:09 PM YEKT 
//


package ru.acs.cat;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.acs.cat package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Cat_QNAME = new QName("http://cat.acs.ru", "Cat");
    private final static QName _CatDescription_QNAME = new QName("http://cat.acs.ru", "Description");
    private final static QName _CatContent_QNAME = new QName("http://cat.acs.ru", "Content");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.acs.cat
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Cat }
     * 
     */
    public Cat createCat() {
        return new Cat();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Cat }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cat.acs.ru", name = "Cat")
    public JAXBElement<Cat> createCat(Cat value) {
        return new JAXBElement<Cat>(_Cat_QNAME, Cat.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cat.acs.ru", name = "Description", scope = Cat.class)
    public JAXBElement<String> createCatDescription(String value) {
        return new JAXBElement<String>(_CatDescription_QNAME, String.class, Cat.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cat.acs.ru", name = "Content", scope = Cat.class)
    public JAXBElement<String> createCatContent(String value) {
        return new JAXBElement<String>(_CatContent_QNAME, String.class, Cat.class, value);
    }

}
