//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.08 at 12:23:09 PM YEKT 
//


package ru.acs.webservices.getcatservices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import ru.acs.cat.Cat;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="catDetails" type="{http://cat.acs.ru}Cat"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "catDetails"
})
@XmlRootElement(name = "GetCatResponse")
public class GetCatResponse {

    @XmlElement(required = true)
    protected Cat catDetails;

    /**
     * Gets the value of the catDetails property.
     * 
     * @return
     *     possible object is
     *     {@link Cat }
     *     
     */
    public Cat getCatDetails() {
        return catDetails;
    }

    /**
     * Sets the value of the catDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cat }
     *     
     */
    public void setCatDetails(Cat value) {
        this.catDetails = value;
    }

}
